'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ar' | 'en';

interface LanguageContextType {
    lang: Language;
    setLang: (l: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
    lang: 'ar',
    setLang: () => { },
    t: (k) => k,
});

// ── قاموس الترجمات ───────────────────────────────────────────────────
export const translations: Record<Language, Record<string, string>> = {
    ar: {
        // Navbar
        'nav.diamonds': 'ألماس',
        'nav.gold': 'ذهب',
        'nav.modern': 'مجوهرات عصرية',
        'nav.labDiamonds': 'ألماس مختبرات',
        'nav.wedding': 'زفاف وخطوبة',
        'nav.gifts': 'هدايا ومناسبات',
        'nav.all': 'تسوّقوا كلّ المجوهرات',
        'nav.about': 'من نحن',
        'nav.contact': 'تواصل معنا',
        'nav.search': 'ابحثي عن المجوهرات...',
        'nav.language': 'عربي',
        'nav.country': 'KSA',
        // Hero (الصفحة الرئيسية)
        'home.hero.badge': 'مجوهرات فاخرة',
        'home.hero.title1': 'أناقة',
        'home.hero.title2': 'بلا حدود',
        'home.hero.subtitle': 'اكتشفي مجموعتنا الحصرية من المجوهرات الفاخرة المصممة بأرقى المعادن والأحجار الكريمة',
        'home.hero.cta': 'تسوّقي الآن',
        'home.hero.builder': 'صمّمي قطعتك',
        'home.featured': 'المجموعة المميزة',
        'home.featured.sub': 'أحدث تصاميمنا الفاخرة',
        'home.viewAll': 'عرض الكل',
        'home.whyUs': 'لماذا Vivelt Gold',
        'home.story.title': 'من نحن',
        'home.story.sub': 'قصتنا مع الجمال',
        'nav.silver': 'فضة',
        'nav.platinum': 'بلاتين',
        'nav.mega.categories': 'الفئات',
        'nav.mega.featured': 'فئات مميزة',
        'nav.mega.metal': 'المعدن',
        'nav.mega.byPrice': 'تسوّقي حسب السعر',
        'nav.mega.karat': 'عيار الذهب',
        'nav.mega.color': 'اللون',
        'nav.mega.types': 'الأنواع',
        'nav.mega.topSelling': 'الأكثر طلباً',
        'nav.mega.collections': 'مجموعات',
        'nav.mega.engageRings': 'خواتم الخطوبة',
        'nav.mega.weddingRings': 'خواتم الزواج',
        'nav.mega.weddingSets': 'مجموعات الزفاف',
        'nav.mega.occasions': 'المناسبات',
        'nav.mega.byBudget': 'تسوّقي حسب الميزانية',
        'nav.mega.whiteGold': 'ذهب أبيض',
        'nav.mega.yellowGold': 'ذهب أصفر',
        'nav.mega.roseGold': 'ذهب وردي',
        'nav.mega.diamondRings': 'خواتم الماس',
        'nav.mega.diamondBracelets': 'أساور الماس',
        'nav.mega.diamondEarrings': 'أقراط الماس',
        'nav.mega.diamondNecklaces': 'قلادات الماس',
        'nav.mega.diamondSets': 'طواقم الماس',
        'nav.mega.goldRings': 'خواتم ذهب',
        'nav.mega.goldBracelets': 'أساور ذهب',
        'nav.mega.goldEarrings': 'أقراط ذهب',
        'nav.mega.goldNecklaces': 'قلادات ذهب',
        'nav.mega.goldBars': 'سبائك ذهب',
        'nav.mega.silverRings': 'خواتم فضة',
        'nav.mega.silverBracelets': 'أساور فضة',
        'nav.mega.silverEarrings': 'أقراط فضة',
        'nav.mega.silverNecklaces': 'قلادات فضة',
        'nav.mega.platinumRings': 'خواتم بلاتين',
        'nav.mega.platinumBracelets': 'أساور بلاتين',
        'nav.mega.platinumEarrings': 'أقراط بلاتين',
        'nav.mega.platinumNecklaces': 'قلادات بلاتين',
        'nav.mega.modernRings': 'خواتم',
        'nav.mega.modernBracelets': 'أساور',
        'nav.mega.modernEarrings': 'أقراط',
        'nav.mega.modernNecklaces': 'قلادات',
        'nav.mega.karat18': 'عيار 18',
        'nav.mega.karat21': 'عيار 21',
        'nav.mega.karat24': 'عيار 24',
        'nav.mega.bestSeller': 'الأكثر مبيعاً',
        'nav.mega.newArrivals': 'وصل حديثاً',
        'nav.mega.unique': 'فريد من نوعه',
        'nav.mega.solitaire': 'سوليتير',
        'nav.mega.twins': 'توينز',
        'nav.mega.halo': 'هالو',
        'nav.mega.sideStone': 'جانبية',
        'nav.mega.weddingSetsLabel': 'أطقم زفاف',
        'nav.mega.forCouple': 'للعريس والعروس',
        'nav.mega.birthday': 'عيد ميلاد',
        'nav.mega.mothersDay': 'يوم الأم',
        'nav.mega.graduation': 'تخرج',
        'nav.mega.valentines': 'عيد الحب',
        'nav.mega.shopAll': 'الأكثر مبيعاً',
        // Shop
        'shop.title': 'المتجر',
        'shop.products': 'منتج',
        'shop.filter': 'تصفية',
        'shop.noProducts': 'لم يتم العثور على منتجات',
        'shop.noProductsSub': 'جرب تغيير معايير التصفية',
        'shop.clearFilters': 'مسح الفلاتر',
        'shop.addToCart': 'أضف للسلة',
        // Product
        'product.notFound': 'المنتج غير موجود',
        'product.backToShop': 'العودة للمتجر',
        'product.new': 'جديد',
        'product.bestSeller': 'الأكثر مبيعاً',
        'product.size': 'المقاس',
        'product.metal': 'المعدن',
        'product.quantity': 'الكمية',
        'product.addToCart': 'أضف للسلة',
        'product.bookConsultation': 'احجز استشارة مجانية',
        'product.addEngraving': 'إضافة نقش (+$150)',
        'product.giftWrap': 'تغليف هدية (+$50)',
        'product.warranty': 'ضمان سنة كاملة',
        'product.freeShipping': 'شحن مجاني للطلبات فوق $1,000',
        'product.returns': 'إرجاع خلال 30 يوم',
        'product.details': 'تفاصيل المنتج',
        'product.related': 'منتجات مشابهة',
        'product.inStock': 'متوفر',
        'product.outOfStock': 'غير متوفر',
        'product.weight': 'الوزن',
        'product.stone': 'الحجر',
        'product.availability': 'التوفر',
        'product.gram': 'غرام',
        'product.loginRequired': 'يرجى تسجيل الدخول أولاً',
        'product.addedToCart': 'تمت الإضافة إلى السلة بنجاح!',
        'product.addError': 'حدث خطأ أثناء الإضافة',
        'product.connectionError': 'تعذر الاتصال بالخادم',
        'product.reviews': 'تقييم',
        'product.engravingLabel': 'النقش',
        // Cart
        'cart.title': 'سلة التسوق',
        'cart.empty': 'سلة التسوق فارغة',
        'cart.emptySub': 'أضف بعض المنتجات للبدء',
        'cart.shopNow': 'تسوق الآن',
        'cart.orderSummary': 'ملخص الطلب',
        'cart.subtotal': 'المجموع الفرعي',
        'cart.shipping': 'الشحن',
        'cart.free': 'مجاني',
        'cart.total': 'الإجمالي',
        'cart.discountCode': 'كود الخصم',
        'cart.enterCode': 'أدخل الكود',
        'cart.apply': 'تطبيق',
        'cart.checkout': 'إتمام الشراء',
        'cart.continueShopping': 'متابعة التسوق',
        'cart.securePayment': 'دفع آمن ومشفر',
        'cart.returns30': 'إرجاع خلال 30 يوم',
        'cart.removeItem': 'حذف',
        'cart.removed': 'تم حذف المنتج من السلة',
        'cart.couponApplied': 'تم تطبيق الكوبون بنجاح! خصم 10%',
        'cart.invalidCoupon': 'كوبون غير صالح',
        'cart.size': 'المقاس',
        'cart.engraving': 'النقش',
        'cart.giftWrap': 'تغليف هدية',
        // Checkout
        'checkout.title': 'إتمام الشراء',
        'checkout.shippingInfo': 'معلومات الشحن',
        'checkout.payment': 'الدفع',
        'checkout.confirm': 'تأكيد الطلب',
        'checkout.firstName': 'الاسم الأول',
        'checkout.lastName': 'الاسم الأخير',
        'checkout.email': 'البريد الإلكتروني',
        'checkout.phone': 'رقم الهاتف',
        'checkout.address': 'العنوان',
        'checkout.city': 'المدينة',
        'checkout.state': 'المحافظة',
        'checkout.zip': 'الرمز البريدي',
        'checkout.chooseState': 'اختر المحافظة',
        'checkout.paymentMethod': 'طريقة الدفع',
        'checkout.creditCard': 'بطاقة ائتمان',
        'checkout.mada': 'مدى',
        'checkout.applePay': 'Apple Pay',
        'checkout.cod': 'الدفع عند الاستلام',
        'checkout.cardNumber': 'رقم البطاقة',
        'checkout.expiry': 'تاريخ الانتهاء',
        'checkout.cvc': 'CVC',
        'checkout.cardName': 'اسم حامل البطاقة',
        'checkout.confirmOrder': 'تأكيد الطلب',
        'checkout.shippingAddress': 'عنوان الشحن',
        'checkout.previous': 'السابق',
        'checkout.next': 'التالي',
        'checkout.processing': 'جاري المعالجة...',
        'checkout.orderSummary': 'ملخص الطلب',
        'checkout.subtotal': 'المجموع الفرعي',
        'checkout.shipping': 'الشحن',
        'checkout.total': 'الإجمالي',
        'checkout.securePayment': 'دفع آمن ومشفر',
        'checkout.agree': 'أوافق على',
        'checkout.terms': 'الشروط والأحكام',
        'checkout.and': 'و',
        'checkout.privacy': 'سياسة الخصوصية',
        'checkout.orderSuccess': 'تم تأكيد الطلب بنجاح! شكراً لتسوقكم معنا.',
        'checkout.orderFailed': 'فشل الطلب',
        'checkout.orderError': 'عذراً، لم نتمكن من معالجة الطلب.',
        // Login
        'login.title': 'تسجيل الدخول',
        'login.username': 'اسم المستخدم',
        'login.password': 'كلمة المرور',
        'login.signIn': 'دخول',
        'login.pleaseWait': 'الرجاء الانتظار...',
        'login.incorrect': 'بيانات الدخول غير صحيحة',
        'login.noAccount': 'ليس لديك حساب؟',
        'login.register': 'إنشاء حساب',
        // Register
        'register.title': 'إنشاء حساب جديد',
        'register.firstName': 'الاسم الأول',
        'register.lastName': 'الاسم الأخير',
        'register.username': 'اسم المستخدم',
        'register.email': 'البريد الإلكتروني',
        'register.password': 'كلمة المرور',
        'register.create': 'إنشاء حساب',
        'register.pleaseWait': 'الرجاء الانتظار...',
        'register.haveAccount': 'لديك حساب بالفعل؟',
        'register.login': 'تسجيل الدخول',
        'register.error': 'حدث خطأ، حاول مرة أخرى',
        // Account
        'account.title': 'حسابي',
        'account.orders': 'طلباتي',
        'account.designs': 'تصميماتي',
        'account.addresses': 'العناوين',
        'account.favorites': 'المفضلة',
        'account.profile': 'الملف الشخصي',
        'account.logout': 'تسجيل الخروج',
        'account.noOrders': 'لا توجد طلبات بعد',
        'account.noDesigns': 'لا توجد تصميمات بعد',
        'account.newDesign': '+ تصميم جديد',
        'account.startDesign': 'ابدأ بتصميم قطعتك الأولى',
        'account.noFavorites': 'لا توجد منتجات مفضلة',
        'account.addAddress': '+ إضافة عنوان',
        'account.addressLabel': 'تسمية العنوان (مثال: المنزل)',
        'account.fullName': 'الاسم الكامل',
        'account.street': 'الشارع',
        'account.city': 'المدينة',
        'account.phoneLabel': 'رقم الهاتف',
        'account.default': 'الافتراضي',
        'account.edit': 'تعديل',
        'account.delete': 'حذف',
        'account.save': 'حفظ',
        'account.cancel': 'إلغاء',
        'account.addAddressTitle': 'إضافة عنوان جديد',
        'account.redesign': 'إعادة تصميم',
        'account.deleteDesign': 'حذف',
        'account.profileFirstName': 'الاسم الأول',
        'account.profileLastName': 'الاسم الأخير',
        'account.profileEmail': 'البريد الإلكتروني',
        'account.profilePhone': 'رقم الهاتف',
        'account.birthDate': 'تاريخ الميلاد',
        'account.saveChanges': 'حفظ التغييرات',
        'account.changePassword': 'تغيير كلمة المرور',
        'account.currentPassword': 'كلمة المرور الحالية',
        'account.newPassword': 'كلمة المرور الجديدة',
        'account.confirmPassword': 'تأكيد كلمة المرور',
        // Order status
        'order.pending': 'معلق',
        'order.processing': 'قيد المعالجة',
        'order.shipped': 'تم الشحن',
        'order.delivered': 'تم التسليم',
        'order.cancelled': 'ملغي',
        // Filter
        'filter.title': 'التصفية',
        'filter.clearAll': 'مسح الكل',
        'filter.sortBy': 'ترتيب حسب',
        'filter.type': 'النوع',
        'filter.all': 'الكل',
        'filter.metal': 'المعدن',
        'filter.stone': 'الحجر الكريم',
        'filter.priceRange': 'نطاق السعر',
        'filter.popular': 'الأكثر شيوعاً',
        'filter.priceAsc': 'السعر: من الأقل للأعلى',
        'filter.priceDesc': 'السعر: من الأعلى للأقل',
        'filter.newest': 'الأحدث',
        // About
        'about.hero.badge': 'Vivelt Gold',
        'about.hero.title1': 'قصتنا مع',
        'about.hero.title2': 'الإبداع',
        'about.hero.sub': 'من ورشة صغيرة إلى مرجع عالمي — رحلة من الشغف والإبداع والتميز',
        'about.story.badge': 'قصتنا',
        'about.story.title1': 'رحلة الإبداع',
        'about.story.title2': 'والتميز',
        'about.values.badge': 'ما يميزنا',
        'about.values.title': 'قيمنا الأساسية',
        'about.values.sub': 'المبادئ التي تحكم كل قرار نتخذه وكل قطعة نصنعها',
        'about.timeline.badge': 'مسيرتنا',
        'about.timeline.title': 'رحلة النجاح',
        'about.cta.title': 'ابدأي رحلتك معنا',
        'about.cta.shop': 'تسوقي الآن',
        'about.cta.contact': 'تواصلي معنا',
        // Contact
        'contact.hero.badge': 'نحن هنا لك',
        'contact.hero.title1': 'تواصل',
        'contact.hero.title2': 'معنا',
        'contact.hero.sub': 'فريقنا جاهز للرد على استفساراتك ومساعدتك',
        'contact.form.title': 'أرسل لنا رسالة',
        'contact.form.name': 'الاسم الكامل',
        'contact.form.email': 'البريد الإلكتروني',
        'contact.form.phone': 'رقم الهاتف',
        'contact.form.subject': 'الموضوع',
        'contact.form.message': 'الرسالة',
        'contact.form.send': 'إرسال الرسالة',
        'contact.form.success': '✓ تم إرسال رسالتك بنجاح! سنتواصل معك قريباً',
        'contact.faq.badge': 'لديك استفسار؟',
        'contact.faq.title': 'الأسئلة الشائعة',
        'contact.phone': 'الهاتف',
        'contact.emailLabel': 'البريد الإلكتروني',
        'contact.address': 'العنوان',
        'contact.hours': 'ساعات العمل',
        // Footer
        'footer.rights': `© ${new Date().getFullYear()} Vivelt gold. جميع الحقوق محفوظة.`,
        'footer.sections': 'الأقسام',
        'footer.help': 'المساعدة',
        'footer.contactUs': 'تواصل معنا',
        'footer.about': 'من نحن',
        'footer.faq': 'الأسئلة الشائعة',
        'footer.returns': 'سياسة الإرجاع',
        'footer.consultation': 'حجز استشارة',
        // Navbar extras
        'nav.design': 'صمّم',
        'nav.cartAria': 'سلة التسوق',
        'nav.favAria': 'المفضلة',
        'nav.designAria': 'صمّم تصميمك',
        'nav.accountAria': 'حسابي',
        'nav.loginAria': 'تسجيل الدخول',
        'nav.adminAria': 'لوحة التحكم',
        'nav.menuAria': 'القائمة',
        'nav.searchAria': 'بحث',
        'nav.country': 'سوريا',
        'nav.new': 'جديد',
        // Mega Menu price ranges
        'nav.price.under1k': 'أقل من $1,000',
        'nav.price.1k5k': '$1,000 - $5,000',
        'nav.price.5k15k': '$5,000 - $15,000',
        'nav.price.over15k': 'أكثر من $15,000',
        'nav.price.under500': 'أقل من $500',
        'nav.price.5002k': '$500 - $2,000',
        'nav.price.over2k': 'أكثر من $2,000',
        'nav.price.under200': 'أقل من $200',
        'nav.price.200500': '$200 - $500',
        'nav.price.over500': 'أكثر من $500',
        'nav.price.under300': 'أقل من $300',
        'nav.price.3001k': '$300 - $1,000',
        'nav.price.over1k': 'أكثر من $1,000',
        // Mega Menu promo labels
        'nav.promo.diamonds': 'تألقي بلا حدود',
        'nav.promo.gold': 'أناقة خالدة',
        'nav.promo.silver': 'جمال نقي',
        'nav.promo.platinum': 'فخامة مطلقة',
        'nav.promo.modern': 'أسلوب حياتك',
        'nav.promo.wedding': 'لحظة لا تُنسى',
        'nav.promo.gifts': 'افرحي من تحبين',
        // Mega Menu promo alt texts
        'nav.promoAlt.diamonds': 'مجوهرات الماس',
        'nav.promoAlt.gold': 'مجوهرات ذهب',
        'nav.promoAlt.silver': 'مجوهرات فضة',
        'nav.promoAlt.platinum': 'مجوهرات بلاتين',
        'nav.promoAlt.modern': 'مجوهرات عصرية',
        'nav.promoAlt.wedding': 'زفاف وخطوبة',
        'nav.promoAlt.gifts': 'هدايا ومناسبات',
        // Product page extras
        'product.home': 'الرئيسية',
        'product.shop': 'المتجر',
        'product.engravingText': 'النقش: "{0}"',
        'product.giftWrapLabel': 'تغليف هدية',
        'product.sizeLabel': 'المقاس',
        // Cart page extras
        'cart.discount': 'الخصم',
        'cart.couponAppliedMsg': '✓ كوبون WELCOME10 مطبق',
        'cart.materialGold': 'ذهب',
        'cart.materialSilver': 'فضة',
        'cart.materialPlatinum': 'بلاتين',
        'cart.materialRoseGold': 'ذهب وردي',
        // Checkout extras
        'checkout.country': 'سوريا',
        'checkout.state.hama': 'حماة',
        'checkout.state.damascus': 'دمشق',
        'checkout.state.aleppo': 'حلب',
        'checkout.state.homs': 'حمص',
        'checkout.state.latakia': 'اللاذقية',
        'checkout.state.tartus': 'طرطوس',
        'checkout.state.idlib': 'إدلب',
        'checkout.state.deir': 'دير الزور',
        'checkout.state.raqqa': 'الرقة',
        'checkout.state.hasaka': 'الحسكة',
        'checkout.state.daraa': 'درعا',
        'checkout.state.suwayda': 'السويداء',
        'checkout.state.quneitra': 'القنيطرة',
        'checkout.state.rif': 'ريف دمشق',
        // Register extras
        'register.errorAccount': 'تعذر إنشاء الحساب',
        // Account extras
        'account.ordersHeading': 'طلباتي',
        'account.designsHeading': 'تصميماتي',
        'account.addressesHeading': 'العناوين',
        'account.favoritesHeading': 'المفضلة',
        'account.profileHeading': 'الملف الشخصي',
        'account.noFavoritesText': 'لا توجد منتجات مفضلة',
        'account.addressDefault': 'الافتراضي',
        'account.addressLabel2': 'عنوان',
        'account.orderDate': 'تاريخ الطلب',
        'account.orderTotal': 'المجموع',
        'account.orderStatus': 'الحالة',
        'account.orderDelivered': 'تم التسليم',
        'account.orderShipped': 'تم الشحن',
        'account.orderProcessing': 'قيد التجهيز',
        'account.orderPending': 'معلق',
        'account.newDesignLink': '+ تصميم جديد',
        'account.redesignLink': 'إعادة تصميم',
        'account.deleteLink': 'حذف',
        'account.addAddressLink': '+ إضافة عنوان',
        'account.addrPlaceholderLabel': 'تسمية العنوان (مثال: المنزل)',
        'account.addrPlaceholderName': 'الاسم الكامل',
        'account.addrPlaceholderStreet': 'الشارع',
        'account.addrPlaceholderCity': 'المدينة',
        'account.addrPlaceholderPhone': 'رقم الهاتف',
        'account.saveBtn': 'حفظ',
        'account.cancelBtn': 'إلغاء',
        'account.editLink': 'تعديل',
        'account.deleteAddressLink': 'حذف',
        // Filter sidebar extras
        'filter.metalGold': 'ذهب',
        'filter.metalSilver': 'فضة',
        'filter.metalPlatinum': 'بلاتين',
        'filter.metalRoseGold': 'ذهب وردي',
        'filter.stoneDiamond': 'ماس',
        'filter.stoneRuby': 'ياقوت أحمر',
        'filter.stoneEmerald': 'زمرد',
        'filter.stoneSapphire': 'ياقوت أزرق',
        'filter.stonePearl': 'لؤلؤ',
        'filter.stoneNone': 'بدون حجر',
        'filter.catRings': 'خواتم',
        'filter.catNecklaces': 'قلادات',
        'filter.catBracelets': 'أساور',
        'filter.catEarrings': 'أقراط',
    },

    en: {
        // Navbar
        'nav.diamonds': 'Diamonds',
        'nav.gold': 'Gold',
        'nav.modern': 'Modern Jewelry',
        'nav.labDiamonds': 'Lab Diamonds',
        'nav.wedding': 'Wedding & Engagement',
        'nav.gifts': 'Gifts & Occasions',
        'nav.all': 'Shop All Jewelry',
        'nav.about': 'About Us',
        'nav.contact': 'Contact Us',
        'nav.search': 'Search jewelry...',
        'nav.language': 'English',
        'nav.country': 'KSA',
        // Hero
        'home.hero.badge': 'Luxury Jewelry',
        'home.hero.title1': 'Elegance',
        'home.hero.title2': 'Redefined',
        'home.hero.subtitle': 'Discover our exclusive collection of luxury jewelry crafted with the finest metals and gemstones',
        'home.hero.cta': 'Shop Now',
        'home.hero.builder': 'Design Yours',
        'home.featured': 'Featured Collection',
        'home.featured.sub': 'Our latest luxury designs',
        'home.viewAll': 'View All',
        'home.whyUs': 'Why Vivelt Gold',
        'home.story.title': 'About Us',
        'home.story.sub': 'Our story of beauty',
        'nav.silver': 'Silver',
        'nav.platinum': 'Platinum',
        'nav.mega.categories': 'Categories',
        'nav.mega.featured': 'Featured',
        'nav.mega.metal': 'Metal',
        'nav.mega.byPrice': 'Shop by Price',
        'nav.mega.karat': 'Gold Karat',
        'nav.mega.color': 'Color',
        'nav.mega.types': 'Types',
        'nav.mega.topSelling': 'Top Selling',
        'nav.mega.collections': 'Collections',
        'nav.mega.engageRings': 'Engagement Rings',
        'nav.mega.weddingRings': 'Wedding Rings',
        'nav.mega.weddingSets': 'Wedding Sets',
        'nav.mega.occasions': 'Occasions',
        'nav.mega.byBudget': 'Shop by Budget',
        'nav.mega.whiteGold': 'White Gold',
        'nav.mega.yellowGold': 'Yellow Gold',
        'nav.mega.roseGold': 'Rose Gold',
        'nav.mega.diamondRings': 'Diamond Rings',
        'nav.mega.diamondBracelets': 'Diamond Bracelets',
        'nav.mega.diamondEarrings': 'Diamond Earrings',
        'nav.mega.diamondNecklaces': 'Diamond Necklaces',
        'nav.mega.diamondSets': 'Diamond Sets',
        'nav.mega.goldRings': 'Gold Rings',
        'nav.mega.goldBracelets': 'Gold Bracelets',
        'nav.mega.goldEarrings': 'Gold Earrings',
        'nav.mega.goldNecklaces': 'Gold Necklaces',
        'nav.mega.goldBars': 'Gold Bars',
        'nav.mega.silverRings': 'Silver Rings',
        'nav.mega.silverBracelets': 'Silver Bracelets',
        'nav.mega.silverEarrings': 'Silver Earrings',
        'nav.mega.silverNecklaces': 'Silver Necklaces',
        'nav.mega.platinumRings': 'Platinum Rings',
        'nav.mega.platinumBracelets': 'Platinum Bracelets',
        'nav.mega.platinumEarrings': 'Platinum Earrings',
        'nav.mega.platinumNecklaces': 'Platinum Necklaces',
        'nav.mega.modernRings': 'Rings',
        'nav.mega.modernBracelets': 'Bracelets',
        'nav.mega.modernEarrings': 'Earrings',
        'nav.mega.modernNecklaces': 'Necklaces',
        'nav.mega.karat18': '18K',
        'nav.mega.karat21': '21K',
        'nav.mega.karat24': '24K',
        'nav.mega.bestSeller': 'Best Sellers',
        'nav.mega.newArrivals': 'New Arrivals',
        'nav.mega.unique': 'Unique Pieces',
        'nav.mega.solitaire': 'Solitaire',
        'nav.mega.twins': 'Twins',
        'nav.mega.halo': 'Halo',
        'nav.mega.sideStone': 'Side Stone',
        'nav.mega.weddingSetsLabel': 'Wedding Sets',
        'nav.mega.forCouple': 'For Bride & Groom',
        'nav.mega.birthday': 'Birthday',
        'nav.mega.mothersDay': "Mother's Day",
        'nav.mega.graduation': 'Graduation',
        'nav.mega.valentines': "Valentine's Day",
        'nav.mega.shopAll': 'Best Sellers',
        // Shop
        'shop.title': 'Shop',
        'shop.products': 'Products',
        'shop.filter': 'Filter',
        'shop.noProducts': 'No products found',
        'shop.noProductsSub': 'Try changing filter criteria',
        'shop.clearFilters': 'Clear Filters',
        'shop.addToCart': 'Add to Cart',
        // Product
        'product.notFound': 'Product not found',
        'product.backToShop': 'Back to Shop',
        'product.new': 'New',
        'product.bestSeller': 'Best Seller',
        'product.size': 'Size',
        'product.metal': 'Metal',
        'product.quantity': 'Quantity',
        'product.addToCart': 'Add to Cart',
        'product.bookConsultation': 'Book Free Consultation',
        'product.addEngraving': 'Add Engraving (+$150)',
        'product.giftWrap': 'Gift Wrap (+$50)',
        'product.warranty': '1 Year Warranty',
        'product.freeShipping': 'Free Shipping over $1,000',
        'product.returns': '30-Day Returns',
        'product.details': 'Product Details',
        'product.related': 'Related Products',
        'product.inStock': 'In Stock',
        'product.outOfStock': 'Out of Stock',
        'product.weight': 'Weight',
        'product.stone': 'Stone',
        'product.availability': 'Availability',
        'product.gram': 'g',
        'product.loginRequired': 'Please login first',
        'product.addedToCart': 'Added to cart successfully!',
        'product.addError': 'Error adding to cart',
        'product.connectionError': 'Could not connect to server',
        'product.reviews': 'reviews',
        'product.engravingLabel': 'Engraving',
        // Cart
        'cart.title': 'Shopping Cart',
        'cart.empty': 'Your cart is empty',
        'cart.emptySub': 'Add some products to get started',
        'cart.shopNow': 'Shop Now',
        'cart.orderSummary': 'Order Summary',
        'cart.subtotal': 'Subtotal',
        'cart.shipping': 'Shipping',
        'cart.free': 'Free',
        'cart.total': 'Total',
        'cart.discountCode': 'Discount Code',
        'cart.enterCode': 'Enter code',
        'cart.apply': 'Apply',
        'cart.checkout': 'Checkout',
        'cart.continueShopping': 'Continue Shopping',
        'cart.securePayment': 'Secure & encrypted payment',
        'cart.returns30': '30-Day Returns',
        'cart.removeItem': 'Remove',
        'cart.removed': 'Product removed from cart',
        'cart.couponApplied': 'Coupon applied successfully! 10% off',
        'cart.invalidCoupon': 'Invalid coupon',
        'cart.size': 'Size',
        'cart.engraving': 'Engraving',
        'cart.giftWrap': 'Gift Wrap',
        // Checkout
        'checkout.title': 'Checkout',
        'checkout.shippingInfo': 'Shipping Info',
        'checkout.payment': 'Payment',
        'checkout.confirm': 'Confirm Order',
        'checkout.firstName': 'First Name',
        'checkout.lastName': 'Last Name',
        'checkout.email': 'Email Address',
        'checkout.phone': 'Phone Number',
        'checkout.address': 'Address',
        'checkout.city': 'City',
        'checkout.state': 'State',
        'checkout.zip': 'Zip Code',
        'checkout.chooseState': 'Choose State',
        'checkout.paymentMethod': 'Payment Method',
        'checkout.creditCard': 'Credit Card',
        'checkout.mada': 'MADA',
        'checkout.applePay': 'Apple Pay',
        'checkout.cod': 'Cash on Delivery',
        'checkout.cardNumber': 'Card Number',
        'checkout.expiry': 'Expiry Date',
        'checkout.cvc': 'CVC',
        'checkout.cardName': 'Cardholder Name',
        'checkout.confirmOrder': 'Confirm Order',
        'checkout.shippingAddress': 'Shipping Address',
        'checkout.previous': 'Previous',
        'checkout.next': 'Next',
        'checkout.processing': 'Processing...',
        'checkout.orderSummary': 'Order Summary',
        'checkout.subtotal': 'Subtotal',
        'checkout.shipping': 'Shipping',
        'checkout.total': 'Total',
        'checkout.securePayment': 'Secure & encrypted payment',
        'checkout.agree': 'I agree to the',
        'checkout.terms': 'Terms & Conditions',
        'checkout.and': 'and',
        'checkout.privacy': 'Privacy Policy',
        'checkout.orderSuccess': 'Order confirmed! Thank you for shopping with us.',
        'checkout.orderFailed': 'Order failed',
        'checkout.orderError': 'Sorry, we could not process your order.',
        // Login
        'login.title': 'Login',
        'login.username': 'Username',
        'login.password': 'Password',
        'login.signIn': 'Sign In',
        'login.pleaseWait': 'Please wait...',
        'login.incorrect': 'Incorrect credentials',
        'login.noAccount': "Don't have an account?",
        'login.register': 'Register',
        // Register
        'register.title': 'Create Account',
        'register.firstName': 'First Name',
        'register.lastName': 'Last Name',
        'register.username': 'Username',
        'register.email': 'Email Address',
        'register.password': 'Password',
        'register.create': 'Create Account',
        'register.pleaseWait': 'Please wait...',
        'register.haveAccount': 'Already have an account?',
        'register.login': 'Login',
        'register.error': 'An error occurred, please try again',
        // Account
        'account.title': 'My Account',
        'account.orders': 'My Orders',
        'account.designs': 'My Designs',
        'account.addresses': 'Addresses',
        'account.favorites': 'Favorites',
        'account.profile': 'Profile',
        'account.logout': 'Logout',
        'account.noOrders': 'No orders yet',
        'account.noDesigns': 'No designs yet',
        'account.newDesign': '+ New Design',
        'account.startDesign': 'Start designing your first piece',
        'account.noFavorites': 'No favorite products',
        'account.addAddress': '+ Add Address',
        'account.addressLabel': 'Address Label (e.g. Home)',
        'account.fullName': 'Full Name',
        'account.street': 'Street',
        'account.city': 'City',
        'account.phoneLabel': 'Phone Number',
        'account.default': 'Default',
        'account.edit': 'Edit',
        'account.delete': 'Delete',
        'account.save': 'Save',
        'account.cancel': 'Cancel',
        'account.addAddressTitle': 'Add New Address',
        'account.redesign': 'Redesign',
        'account.deleteDesign': 'Delete',
        'account.profileFirstName': 'First Name',
        'account.profileLastName': 'Last Name',
        'account.profileEmail': 'Email Address',
        'account.profilePhone': 'Phone Number',
        'account.birthDate': 'Birth Date',
        'account.saveChanges': 'Save Changes',
        'account.changePassword': 'Change Password',
        'account.currentPassword': 'Current Password',
        'account.newPassword': 'New Password',
        'account.confirmPassword': 'Confirm Password',
        // Order status
        'order.pending': 'Pending',
        'order.processing': 'Processing',
        'order.shipped': 'Shipped',
        'order.delivered': 'Delivered',
        'order.cancelled': 'Cancelled',
        // Filter
        'filter.title': 'Filter',
        'filter.clearAll': 'Clear All',
        'filter.sortBy': 'Sort By',
        'filter.type': 'Type',
        'filter.all': 'All',
        'filter.metal': 'Metal',
        'filter.stone': 'Gemstone',
        'filter.priceRange': 'Price Range',
        'filter.popular': 'Most Popular',
        'filter.priceAsc': 'Price: Low to High',
        'filter.priceDesc': 'Price: High to Low',
        'filter.newest': 'Newest',
        // About
        'about.hero.badge': 'Vivelt Gold',
        'about.hero.title1': 'Our Story of',
        'about.hero.title2': 'Creativity',
        'about.hero.sub': 'From a small workshop to a global reference — a journey of passion, creativity, and excellence',
        'about.story.badge': 'Our Story',
        'about.story.title1': 'Journey of Creativity',
        'about.story.title2': '& Excellence',
        'about.values.badge': 'What Sets Us Apart',
        'about.values.title': 'Our Core Values',
        'about.values.sub': 'The principles that guide every decision we make and every piece we craft',
        'about.timeline.badge': 'Our Journey',
        'about.timeline.title': 'Road to Success',
        'about.cta.title': 'Start Your Journey With Us',
        'about.cta.shop': 'Shop Now',
        'about.cta.contact': 'Contact Us',
        // Contact
        'contact.hero.badge': "We're Here For You",
        'contact.hero.title1': 'Contact',
        'contact.hero.title2': 'Us',
        'contact.hero.sub': 'Our team is ready to answer your queries and help you find the perfect jewelry',
        'contact.form.title': 'Send Us a Message',
        'contact.form.name': 'Full Name',
        'contact.form.email': 'Email Address',
        'contact.form.phone': 'Phone Number',
        'contact.form.subject': 'Subject',
        'contact.form.message': 'Message',
        'contact.form.send': 'Send Message',
        'contact.form.success': '✓ Your message was sent successfully! We will contact you soon',
        'contact.faq.badge': 'Have a Question?',
        'contact.faq.title': 'Frequently Asked Questions',
        'contact.phone': 'Phone',
        'contact.emailLabel': 'Email',
        'contact.address': 'Address',
        'contact.hours': 'Working Hours',
        // Footer
        'footer.rights': `© ${new Date().getFullYear()} Vivelt gold. All rights reserved.`,
        'footer.sections': 'Collections',
        'footer.help': 'Help',
        'footer.contactUs': 'Contact Us',
        'footer.about': 'About Us',
        'footer.faq': 'FAQ',
        'footer.returns': 'Return Policy',
        'footer.consultation': 'Book Consultation',
        // Navbar extras
        'nav.design': 'Design',
        'nav.cartAria': 'Shopping Cart',
        'nav.favAria': 'Favorites',
        'nav.designAria': 'Design Yours',
        'nav.accountAria': 'My Account',
        'nav.loginAria': 'Login',
        'nav.adminAria': 'Dashboard',
        'nav.menuAria': 'Menu',
        'nav.searchAria': 'Search',
        'nav.country': 'Syria',
        'nav.new': 'New',
        // Mega Menu price ranges
        'nav.price.under1k': 'Under $1,000',
        'nav.price.1k5k': '$1,000 - $5,000',
        'nav.price.5k15k': '$5,000 - $15,000',
        'nav.price.over15k': 'Over $15,000',
        'nav.price.under500': 'Under $500',
        'nav.price.5002k': '$500 - $2,000',
        'nav.price.over2k': 'Over $2,000',
        'nav.price.under200': 'Under $200',
        'nav.price.200500': '$200 - $500',
        'nav.price.over500': 'Over $500',
        'nav.price.under300': 'Under $300',
        'nav.price.3001k': '$300 - $1,000',
        'nav.price.over1k': 'Over $1,000',
        // Mega Menu promo labels
        'nav.promo.diamonds': 'Shine Without Limits',
        'nav.promo.gold': 'Timeless Elegance',
        'nav.promo.silver': 'Pure Beauty',
        'nav.promo.platinum': 'Absolute Luxury',
        'nav.promo.modern': 'Your Lifestyle',
        'nav.promo.wedding': 'An Unforgettable Moment',
        'nav.promo.gifts': 'Make Her Happy',
        // Mega Menu promo alt texts
        'nav.promoAlt.diamonds': 'Diamond Jewelry',
        'nav.promoAlt.gold': 'Gold Jewelry',
        'nav.promoAlt.silver': 'Silver Jewelry',
        'nav.promoAlt.platinum': 'Platinum Jewelry',
        'nav.promoAlt.modern': 'Modern Jewelry',
        'nav.promoAlt.wedding': 'Wedding & Engagement',
        'nav.promoAlt.gifts': 'Gifts & Occasions',
        // Product page extras
        'product.home': 'Home',
        'product.shop': 'Shop',
        'product.engravingText': 'Engraving: "{0}"',
        'product.giftWrapLabel': 'Gift Wrap',
        'product.sizeLabel': 'Size',
        // Cart page extras
        'cart.discount': 'Discount',
        'cart.couponAppliedMsg': '✓ Coupon WELCOME10 applied',
        'cart.materialGold': 'Gold',
        'cart.materialSilver': 'Silver',
        'cart.materialPlatinum': 'Platinum',
        'cart.materialRoseGold': 'Rose Gold',
        // Checkout extras
        'checkout.country': 'Syria',
        'checkout.state.hama': 'Hama',
        'checkout.state.damascus': 'Damascus',
        'checkout.state.aleppo': 'Aleppo',
        'checkout.state.homs': 'Homs',
        'checkout.state.latakia': 'Latakia',
        'checkout.state.tartus': 'Tartus',
        'checkout.state.idlib': 'Idlib',
        'checkout.state.deir': 'Deir ez-Zor',
        'checkout.state.raqqa': 'Raqqa',
        'checkout.state.hasaka': 'Hasaka',
        'checkout.state.daraa': 'Daraa',
        'checkout.state.suwayda': 'Suwayda',
        'checkout.state.quneitra': 'Quneitra',
        'checkout.state.rif': 'Rif Dimashq',
        // Register extras
        'register.errorAccount': 'Could not create account',
        // Account extras
        'account.ordersHeading': 'My Orders',
        'account.designsHeading': 'My Designs',
        'account.addressesHeading': 'Addresses',
        'account.favoritesHeading': 'Favorites',
        'account.profileHeading': 'Profile',
        'account.noFavoritesText': 'No favorite products',
        'account.addressDefault': 'Default',
        'account.addressLabel2': 'Address',
        'account.orderDate': 'Order Date',
        'account.orderTotal': 'Total',
        'account.orderStatus': 'Status',
        'account.orderDelivered': 'Delivered',
        'account.orderShipped': 'Shipped',
        'account.orderProcessing': 'Processing',
        'account.orderPending': 'Pending',
        'account.newDesignLink': '+ New Design',
        'account.redesignLink': 'Redesign',
        'account.deleteLink': 'Delete',
    },
};

// ── Provider ─────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<Language>('ar');

    useEffect(() => {
        const saved = localStorage.getItem('vivelt-lang') as Language | null;
        if (saved === 'ar' || saved === 'en') setLangState(saved);
    }, []);

    const setLang = (l: Language) => {
        setLangState(l);
        localStorage.setItem('vivelt-lang', l);
        // تحديث dir و lang على <html>
        document.documentElement.lang = l;
        document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr';
    };

    const t = (key: string): string =>
        translations[lang][key] ?? translations['ar'][key] ?? key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

// ── Hook ─────────────────────────────────────────────────────────────
export function useLanguage() {
    return useContext(LanguageContext);
}
